# -*- coding: utf-8 -*-
"""Cópia de Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16rgKHRdKFLX4KwwBRcv8ShxBALGaquas
"""

import google.generativeai as genai
import urllib.request

GOOGLE_API_KEY="AIzaSyD-RBOn1Gu7BcARyIqDdaGjqO_uBb1_rL8"
genai.configure(api_key=GOOGLE_API_KEY)

generation_config = {
  "temperature": 0.0,
  "top_p": 0.95,
  "top_k": 0
}

safety_settings = [
  {
    "category": "HARM_CATEGORY_HARASSMENT",
    "threshold": "BLOCK_NONE"
  },
  {
    "category": "HARM_CATEGORY_HATE_SPEECH",
    "threshold": "BLOCK_NONE"
  },
  {
    "category": "HARM_CATEGORY_SEXUALLY_EXPLICIT",
    "threshold": "BLOCK_NONE"
  },
  {
    "category": "HARM_CATEGORY_DANGEROUS_CONTENT",
    "threshold": "BLOCK_NONE"
  },
]

model = genai.GenerativeModel(model_name="gemini-1.5-pro-latest",
                              generation_config=generation_config,
                              safety_settings=safety_settings)

prompt_parts = [
  "Qual é a placa completo do carro nessa foto em formato brasileiro com sete caracteres?",
  "Imagem ",
  genai.upload_file("GAE0244.jpg"),
  "A placa desse veículo é GAE0244",
  "Imagem ",
  genai.upload_file("POX4G21.jpg"),
  "A placa desse veículo é POX4G21",
  "Imagem ",
  genai.upload_file("RHA0A01.jpg"),
  "A placa desse veículo éRHA0A01",
  "Imagem ",
  genai.upload_file("CIV2484.jpg"),
  "Qual a placa desse veiculo? ",
]

response = model.generate_content(prompt_parts)
print(response.text)